In [1]:
import datetime as dt
import pandas as pd
from util import get_data, plot_data  	
import

In [20]:
symbol = "JPM"
sd=dt.datetime(2008, 1, 1)
ed=dt.datetime(2009,12,31) 
sv = 100000
orders=[]
profit = 0

In [100]:
price = get_data([symbol], pd.date_range(sd, ed)).reset_index().rename(columns={'index': 'Date'})
del price['SPY']
price['Order'] = None
price.loc[0, 'Order'] = "BUY"
price['Shares'] = 0 
price.loc[0, 'Shares'] = 1000

for i, col in price[1:].iterrows():
    date = col['Date']
    today_price = col[symbol]
    order = price.at[i, 'Order']
    prev_hold = price.at[i-1, 'Shares']
    curr_hold = price.at[i, 'Shares']
    
    if i < len(price) - 1:
        tmrw_price = price.iloc[i + 1][symbol]

        if tmrw_price > today_price:
            if prev_hold == 1000:
                price.at[i, 'Order'] = "HOLD"
                price.at[i, 'Shares'] = prev_hold
            elif prev_hold == 0: 
                price.at[i, 'Order'] = "BUY"
                price.at[i, 'Shares'] = prev_hold + 1000
            elif prev_hold == -1000:
                price.at[i, 'Order'] = "BUY"
                price.at[i, 'Shares'] = prev_hold + 2000
                
        elif tmrw_price < today_price:
            if prev_hold <= -1000:
                price.at[i, 'Order'] = "HOLD"
                price.at[i, 'Shares'] = prev_hold
            elif prev_hold == 0:     
                price.at[i, 'Order'] = "SELL"
                price.at[i, 'Shares'] = prev_hold - 1000
            elif prev_hold == 1000:
                price.at[i, 'Order'] = "SELL"
                price.at[i, 'Shares'] = prev_hold - 2000
        else: 
            price.at[i, 'Order'] = "HOLD"
    else:
        price.at[i, 'Order'] = "HOLD"
        price.at[i, 'Shares'] = prev_hold
    #print(price.at[i, 'Order'])

'''
strategy: buy today if the day after price is lower
            sell today if the day after price is higher
            hold if equal
'''

          Date    JPM Order  Shares
0   2008-01-02  38.47   BUY    1000
1   2008-01-03  38.20  SELL   -1000
2   2008-01-04  37.33   BUY       0
3   2008-01-07  37.71  SELL   -1000
4   2008-01-08  36.21   BUY       0
..         ...    ...   ...     ...
500 2009-12-24  39.91  SELL   -1000
501 2009-12-28  39.75  HOLD   -1000
502 2009-12-29  39.53   BUY       0
503 2009-12-30  39.57   BUY       0
504 2009-12-31  39.70  HOLD       0

[505 rows x 4 columns]

In [ ]:
for i, row in price.iterrows():
    today = row['Date']
    price = row[symbol]